[package]
name = "pestr"
version = "0.1.0"
authors = ["Andrew Dawson <ajdawson@acm.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "~2.33", features = ["yaml"] }
serde_json = "~1.0"